const repeatTimes = 50;

const provinces = [
'An_Giang',
'Bà_Rịa_Vũng_Tàu',
'Bắc_Giang',
'Bắc_Kạn',
'Bạc_Liêu',
'Bắc_Ninh',
'Bến_Tre',
'Bình_Định',
'Bình_Dương',
'Bình_Phước',
'Bình_Thuận',
'Cà_Mau',
'Cần_Thơ',
'Cao_Bằng',
'Đà_Nẵng',
'Đắk_Lắk',
'Đắk_Nông',
'Điện_Biên',
'Đồng_Nai',
'Đồng_Tháp',
'Gia_Lai',
'Hà_Giang',
'Hà_Nam',
'Hà_Nội',
'Hà_Tĩnh',
'Hải_Dương',
'Hải_Phòng',
'Hậu_Giang',
'Hòa_Bình',
'Hưng_Yên',
'Khánh_Hòa',
'Kiên_Giang',
'Kon_Tum',
'Lai_Châu',
'Lâm_Đồng',
'Lạng_Sơn',
'Lào_Cai',
'Long_An',
'Nam_Định',
'Nghệ_An',
'Ninh_Bình',
'Ninh_Thuận',
'Phú_Thọ',
'Phú_Yên',
'Quảng_Bình',
'Quảng_Nam',
'Quảng_Ngãi',
'Quảng_Ninh',
'Quảng_Trị',
'Sóc_Trăng',
'Sơn_La',
'Tây_Ninh',
'Thái_Bình',
'Thái_Nguyên',
'Thanh_Hóa',
'Thừa_Thiên_Huế',
'Tiền_Giang',
'Thành_phố_Hồ_Chí_Minh',
'Trà_Vinh',
'Tuyên_Quang',
'Vĩnh_Long',
'Vĩnh_Phúc',
'Yên_Bái'
]

const userList = [
    "beeldhoek7nnuq5",
    "u1ic0ussow",
    "rfireblogwc8nie",
    "snowgardenupy7vm",
    "lalo5890v2y48dd3",
    "servirana3pqil4",
    "roztikat6con7e",
    "CamsCoarmahek071m64",
    "savnwpmnrb",
    "Fatarellii2748i",
    "wallapizza8h2hq9",
    "mejrimak8w24m",
    "afasicz7oxoq",
    "expozicenkrcr0",
    "slagimqc1bk",
    "punjenij1ex1k",
    "s6p5annc320pm",
    "caratzafma3d",
    "Gorzewo821uk2",
    "edubixiszacaru615h3",
    "velvetpuffinrst639",
    "ddigrifaf61et8f",
    "curarleswcjz8o",
    "sel3ad3gxu9p",
    "vrsnikew768b6",
    "amyliajoy2zg2ws",
    "solventia0vbfxs",
    "liosanna3feubk",
    "ivandmj5662j72",
    "96RMY7stts4o",
    "seisoenwwdxys",
    "vanibenitezxsntxs",
    "Deneffehalmwg9u92",
    "SonScoorrypesc6py3l",
    "esmentoar5dc0a5",
    "gadwyniqyjpv1",
    "menshidizda6pg",
    "sensoveganfzkz5x",
    "slemmegbcj2b",
    "fam48fan4owco0",
    "florecen5nmo4m",
    "ferliene7e6fug",
    "heiv4g9akw",
    "gaterittgkefo3",
    "maszlagpm9gsn",
    "Rodopih21wj4c",
    "hangulatokt02d",
    "Maczkoqjfw92",
    "corsavasra30b4",
    "dazzledjemimkfb6",
    "Biaffipsem9mpy7",
    "suiseeGuP7z41re",
    "zavitushkada77ldo8",
    "LVII4c40zc",
    "ymogelwch3u7h17",
    "arnaudhussonz6xpc4",
    "Findlayjnw3q9",
    "Previtiwyuys",
    "xpoopieex72u42z",
    "fodha632xmp",
    "eslagatat3ugbdd",
    "evame29sufu",
    "krajankapln2qq",
    "sidequesh10kv",
    "lebrauts36ge7p",
    "striare2roxg0",
    "Formisanoblond6",
    "tenorizeskcltfq",
    "irraDeicewsz3z54q",
    "Letourdi3mp4xa",
    "hImbolcxabnuo",
    "uppdrifizyyxy1",
    "krznenihow7vzt",
    "calandrivtcjrn",
    "zaslonin6mn5",
    "optiralomi6r82",
    "noeliacanoqn4hix",
    "Moknihw3zeq",
    "Forsthelm0mzb9i",
    "vlasblondixsjng",
    "OrinoAfformjz28hx",
    "uspavajte1mdevz",
    "Redrwo8l86",
    "lasongudytwx",
    "odrpansev5fh",
    "Gaelaiddh9kq50",
    "grenadere358vzk",
    "gartanrol7h1",
    "stranogk4ayli",
    "Anerrumlellers0d0ch",
    "privozi23bit1",
    "palissars544kn7",
    "zahovd55zxd",
    "royantunyco1",
    "KnifyTeefobv6gy",
    "gliocaisfv999d",
    "TexSitimpaiptqlhgf5",
    "ebucayigg1a5b",
    "velvetpuffin5isrxn",
    "semliojach5m8p",
    "mjoja94x2jd",
    "Kegelmanne1r760",
    "alleygambolmwci9u",
    "laysbykim138czri9u",
    "kutumiatb0bq0",
    "horkonanduckh9",
    "Salzsncv1c",
    "henwebochhytwr6",
    "krajankaf7sukm",
    "PymnpokePepe35vur",
    "palaisemkc05t9",
    "frexystud4v4zaa",
    "grenjarebziq2",
    "wthrlyeul7ex",
    "esumareohholc",
    "pailaroco3drxs4",
    "Clasuralaspxyftca",
    "marcela409cz95nq",
    "Grobnikiy4wl7a",
    "kaleikanagzd0xb",
    "Grammauta168pi7",
    "cooneyn87z7a",
    "gymhlygau75k9kk",
    "addelyclexk0mke",
    "zaklinja28jvvr",
    "Stiglitzcqotws",
    "dnvietboiyr9gps",
    "kiimbo56m37t",
    "fdvihd5jaha",
    "epilogamsoc6n4",
    "Abnotheinfeno7u4iz0",
    "Ardenyznio1m",
    "Gfalliaep33",
    "hedfryd5lvxrp",
    "tehnicistagqqfe",
    "NeewlyWervcpyv1",
    "gomagfma7rw",
    "cvetkamiqpyg1e",
    "aycomoduelelzyzvb",
    "moralizemp7rsmd",
    "truculentzttnkj",
    "seseluk18ausa",
    "thirteendays6izc97",
    "trijeznomi4km4e",
    "Teuernzb1ic8",
    "silila52ta7b",
    "Rimdaugafnl96p",
    "thismygroup89i79t",
    "jetrvamafldfpe",
    "cristolgospol956or",
    "Janusifpp8xy",
    "judicanjbypqj",
    "PONFhf932h",
    "elgransaltoyx4vcs",
    "tallecerkauru6",
    "toneaan3j5i",
    "kerjap0dqgcn",
    "Nagelmannbtk2du",
    "geragd2w0x7w",
    "genelecepoicyii93sm",
    "sylvanhusfs7f41",
    "wedelnu2kj3g",
    "thalamip1erix",
    "arosymonondymsq",
    "stephett81932",
    "reporteactivo9f4w64",
    "gyrliog8x8xkl",
    "ideokslalian1lhut",
    "Gateteivim5x",
    "etoilenoirubyhjw",
    "Arcallundollaadon1p",
    "erthanjel4zmzih",
    "kicentizevmhqy",
    "philisteecwyt7b",
    "infiliglype85tq8t",
    "scuiparevpgh5c",
    "khalfi132akd7",
    "tekeerto86vc",
    "dywads1r4wg",
    "brokeneverxi7zk8",
    "hualygnstgh",
    "aspromotdl1xd1",
    "ThaseLayets63arzt",
    "roleassesty60iqq7",
    "dobbsamzl0dzu",
    "maledissedlpars",
    "kmptinfoegqsl1",
    "Pirancihua6uv",
    "na1e0krhyd",
    "gyo1mazvnr04",
    "hulatsie19wv",
    "nekielskiegx0ph",
    "Hadspenefqjfl",
    "klaarstaoxz8c",
    "wezenlijkvyakdq",
    "blogchezzazazpng44",
    "tranowniartom5d",
    "Mandibelnw416yz",
    "Pahlet821n2p",
    "Neifyorareeeogxfa",
    "odrpanzmikjm",
    "ingy21k76xd8",
    "danssonculncqhre",
    "alex4ever9awoaj",
    "kiracheltftfzz",
    "gettonesud1iq",
    "esceradas6y818i",
    "stellaerransg3nkw3",
    "gaipsearrireecxyppt",
    "Afonwenthbcma",
    "onemoreonce2jct1f",
    "infiliglypejynlak",
    "ribozimesd31owh",
    "telexetzasqrta",
    "Blancatoj5wvnu",
    "Suedderie5s5e78",
    "infochiapaswvd166",
    "expoedusuper22mdlq",
    "demiantas41m95f",
    "claraportlandlygpub",
    "convito9le8ng",
    "strampaskajydj",
    "redcherryyy2z8nk7",
    "furstanumfdvxmh",
    "matholympiaso6u0g",
    "pangsixsfmte",
    "jesskh1k011n",
    "nariguetod05i3t",
    "onmisbare5a0y83",
    "encenentsodroy",
    "realcummapmwzz7",
    "pafkampox86zbf",
    "lankataliabnh8g7",
    "l4en5uj0liz8",
    "wuksnickil3puzw",
    "Russignane9i3j6",
    "muahtaraqctlv4",
    "defuntarsds1kd4",
    "deilf783elb",
    "islamlatino39mnyy",
    "fillesakkq8m5z",
    "borokrzlu7s",
    "Jayme0h35kb",
    "blestappujak",
    "bluedeefulqle5cd",
    "tubamai55xem",
    "rotorinisb9ely5",
    "jabalcsai19bpyx",
    "e4ea4hsg2bl",
    "wijkhoofds9hzjq",
    "amphoraeij7xje",
    "QIQ6GA7dggu0",
    "weetbaari3shv1",
    "kta1laq0ogs9",
    "coklah212f7e",
    "Worttreue5j6p39",
    "WedoIrritteijz3a0",
    "ugodnejezdtrft",
    "Spemypept9qnhu8",
    "talhsw2t1jd",
    "sunchalesadedds",
    "flekkutzy318s",
    "Dimbachvc7609",
    "miximagenesbaezls",
    "Stole75ae50",
    "m11depto4029t6vpi",
    "dairabs245c",
    "garfisseaiwgp2",
    "flippimp24zkbgt6",
    "nabacalo4sov4g",
    "pabayaan0po818",
    "malachi0721682b8l",
    "Vorabends05mcw",
    "Kaufweller58cew",
    "crossings100k9re6wm",
    "brubbentraurfswh9oq",
    "gospode0mb0dg",
    "urbanizadrib10",
    "ledenavbdf67b",
    "saeneerbh2y",
    "Quogsweenueas367t",
    "xolildanitxow723ie",
    "formingatb1tps",
    "gere64416fax",
    "mypeKneemiab4l71s",
    "thewritehandmly8f0",
    "Savello1e7th7",
    "Skontroxex2q2",
    "Sciecymmerse46pqr",
    "kvazarx7fw7t",
    "teskobno0z9qxn",
    "jwfarnspk0rzd",
    "sekstetaoc2ua8",
    "demagogo30feie",
    "Jeretinov0yamnu",
    "umolio0cic1v",
    "neuslovnol5c18l",
    "epileeru9e7ic",
    "intrigirab2g6at",
    "delolairunj2ppnu",
    "dialonn4osxw",
    "upwindjjjkul",
    "negligimtojn9k",
    "Torr8yv0my",
    "khumbeloulz05j",
    "Enzyncaccumepeaj3",
    "auguretzdk8lr7",
    "vivianwyey8ass",
    "lipaswisvm7ac",
    "Yeuillaznd4xrn",
    "yawlctg69e",
    "banyam7t04m6",
    "roepnaam4dzz2d",
    "snowmancherryq5h6hb",
    "kerjap11387v",
    "namslm2a35o",
    "nyplantaf8okxt",
    "cuerdodowxox",
    "precioznaveed1f",
    "Suchwortc6o3kv",
    "fordauj8wtkl",
    "genhadochnh7rdl",
    "Keerllep7ru",
    "kutumiaqkjk5r",
    "senk3puddc",
    "enkeltlov6agrwu",
    "pentelicoaxfoo1",
    "lasicomzq3ctr",
    "tekdragon2000iq08vk",
    "allipeterseni4k6dh",
    "bikeaddicteslbfpa6",
    "tarjeterokt5pbv",
    "Haitk8e2qh",
    "dienste4fx019",
    "t1quj7s4z",
    "vessamenttsukc2",
    "fneje71gzmb43",
    "zamerajteh2u1vd",
    "dymi7mahf3",
    "vinetelecyt5ft",
    "cowitachitz0wga",
    "sajcv5otluf",
    "touwerijxnvdzu",
    "topsyturvyjo1u1xo1",
    "sizizwelagbymfm",
    "dymivwsruf",
    "pardete20hejqfe",
    "rolinski404rjn91z",
    "bickens3g0yc",
    "mrseykericdxts",
    "ood4lvcly45",
    "zgubitilir1bu",
    "maurypasquiersniz6v",
    "Bierkrug6k0egl",
    "Zollesi5110lj",
    "Camerauu3fnv3",
    "xonexmistakex19bpew",
    "cromemkrq0vq",
    "laajt6yn12",
    "potreseni6ssdt2",
    "ssawkowymh8y3z",
    "dotistalkingfl1se6",
    "gehuilds5tqal",
    "danalyn1972keyz1f",
    "mivuto8nt33f",
    "Kisslegg0lvfe1",
    "livrareunz09d",
    "unetengb5ny",
    "Rosseaudtw83h",
    "cumulava4p2eko",
    "badappleiconsq165nm",
    "oritavengodq1f5t",
    "alerttwireeteepi5",
    "royalesfahc2i",
    "Holandkam5lyezp",
    "alogadas9p65ij",
    "Kontentenmxzada",
    "clancy5a9hfd3",
    "Sepsydype47fxe6",
    "Nibbiolam1vont",
    "zadatexpw0z6",
    "gisluxutavxg",
    "gwlinghyc5kd",
    "pulpitesxyzvn",
    "Inhistscani2w3jqw",
    "trigineayq5fo",
    "sacciformujiucg",
    "Strtenicig9g40d",
    "lhomepereta4nqyyp",
    "derneicjole9",
    "serahk2xvi7",
    "Ardenyps0tvx",
    "RMICN0hyduh",
    "musicalizadoaj5w57",
    "espita1cag33",
    "zavpitngsiqa",
    "biobamamay7kuh5",
    "EDissusia689u9l",
    "1day8dj721",
    "laibino01uez2",
    "tabali4sxcy6",
    "dispurepnoy7x2u5f",
    "Calenberge016i2",
    "Albicini2vtkym",
    "Textmodulnwe14b",
    "podwijkahcrxq1",
    "Dainiuszwgzyb",
    "Somalig2m2oj",
    "camosadaqrk89w",
    "perrecatsz5jj4g",
    "xstudd3bwymcz",
    "gezwinderrtdek6",
    "rookpanvqjjpo",
    "SHANCESAj0vyks",
    "Vallstedtwfjl8c",
    "zigabootie5kohfe",
    "lelidiskiq2diln",
    "kennethneth8gecdu",
    "tylerwetrust9xo529",
    "ripaspips8lncbp",
    "eseid9ulgb",
    "dongavnnxvk",
    "sacabalatt6i2r",
    "meerminu5x5i7",
    "swizzersa4ezy3",
    "resurface7hysbs",
    "fhlathailpz9std",
    "oskuliertvxyh93",
    "Katawertytxwzf",
    "kieferorligk",
    "duby5yczta",
    "t3z2i18p26i",
    "staingexa7l2",
    "toanhcwrq1p",
    "serranotenisdyuvz2",
    "svrgnutih419mf7",
    "vanya876ydwhps",
    "objeteSteftyjtiws",
    "nawiredslhs",
    "totalvrak11tsy7",
    "Darlachpcbov",
    "Nosdeoxjkoyx",
    "roadside0dhheh",
    "bigobroonryhvwdcm",
    "malasmaneraskthcq2",
    "homnibwsuwk97y",
    "hayer8zingd",
    "xemxchik7keh69",
    "granulit2ee30b",
    "librik87we6",
    "sakuraflorealtnhjt2",
    "tulastega7bp6d4",
    "veneravav2udm2",
    "Occatreraqyjcr7",
    "helwigwac4hn",
    "kuncikanw8g03h",
    "bleekgoed6znmql",
    "veneravacxodty",
    "nemotendp4ela",
    "Imikhubacxsg4s",
    "folignapvl39j",
    "infefummapa06oy",
    "solcuitixevac",
    "Meredithagu6zk2",
    "Tagesauge4cvg37",
    "willq88ogx9zv",
    "sajcvzjwf1r",
    "danielwingnkxxoa",
    "TumsMaimumnzvkuk2",
    "femeiescngwtgf",
    "ujedalihhft51",
    "turistika2uueup",
    "encarenta1h426k",
    "infersieowu7e",
    "rudyrobbobaqkzrf",
    "all4uj5zt5g",
    "eresh5lij0",
    "rebalotatunfdy6",
    "uzvodnods3nc7",
    "gundytis54iqln",
    "Agollkj2e8",
    "centellemp5j4x",
    "pieterfrancissef5ij",
    "saptarsak0g6u",
    "scheurde8p1dcq",
    "tarsainnfhkoay",
    "Belasn3psc0",
    "zotavitxsm71b",
    "trusantaxwjrb2",
    "blomplanta5rrsu",
    "CymnCymnhippnz6ls",
    "DCLVII4y7rv4",
    "azilianadzfq0k",
    "RTVSchyi8m",
    "glucke05y39w",
    "epiklezaccfspe",
    "G8Qsyp7a8",
    "corbavasrbrylw",
    "calbhaighuw6m0i",
    "krigethao73m"
  ]


const getRandomInt = (min, max) => {
    min = Math.ceil(min)
    max = Math.floor(max)
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

const getRandomString = (length) => {
    const possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let result = "";
    for (let i=0; i<length; i++) 
        result += possible.charAt(getRandomInt(0, possible.length-1));
    return result
}

const getRandomSearchString = () => {
    const listSearchString = ['Jacket', 'Boot', 'Backpack', 'Red Wing Iron Ranger Boot', 'Duckworth Woolfill Jacket'];
    const randomIndex = getRandomInt(0, listSearchString.length-1);
    return listSearchString[randomIndex];
} 

const getRandomProvince = () => {
    const randomIndex = getRandomInt(0, provinces.length-1);
    return provinces[randomIndex]
}

context('Cypress for em', () => {
    beforeEach(() => {
      cy.visit('http://127.0.0.1:1111')
    })
    for (let i=0; i<repeatTimes; i++) {
        it('can add to carts', () => {
            let productId = getRandomInt(1, 6)    
            if (productId == 2) productId += 1  
            cy.get(':nth-child(' + productId +  ')> .thumbnail > .product_wrapper > a > .product-title').should('be.visible').click()
            // cy.get(':nth-child(3) > .btn').should('be.visible').click()
            let quantity = getRandomInt(0, 4)
            for (let j=0; j<quantity; j++) {
                cy.get('#container > div > div > div > div.col.s12.m6.pull-right > div > div.col.s10.productOptions > div > span:nth-child(3) > button').should('be.visible').click()
            }
            cy.get('.btnAddToCart > .btn').should('be.visible').click()
        })
    }

    for (let i=0; i<repeatTimes; i++) {
        it('can search for products', () => {
            cy.get('#frm_search').should('be.visible').type(getRandomSearchString())
            cy.get('#btn_search').should('be.visible').click()
            cy.get('#container > div > div.productsWrapper.col.m8.offset-m2 > div.row.product-layout > div > div > div > a > h3').first().click()
        })
    }

    for (let i=0; i<repeatTimes; i++) {
        it('can click to another products of other categories', () => {
            let categoryId = getRandomInt(1, 3)
            cy.get('.col > ul > :nth-child(' + categoryId + ') > a').should('be.visible').click()
        })
    }


    for (let i=0; i<repeatTimes; i++) {
        it('can pay for products', () => {
            let productId = getRandomInt(1, 6);
            if (productId == 2) productId += 1
            cy.get(':nth-child(' + productId + ') > .thumbnail > .product_wrapper > a > .product-title').click()
            let quantity = getRandomInt(0, 4)
            for (let j=0; j<quantity; j++) {
                cy.get('#container > div > div > div > div.col.s12.m6.pull-right > div > div.col.s10.productOptions > div > span:nth-child(3) > button').should('be.visible').click()
            }
            // cy.get(':nth-child(3) > .btn').should('be.visible').click();
            // cy.get(':nth-child(3) > .btn').click()
            cy.get('.btnAddToCart > .btn').should('be.visible').click()
            // for (let j=0; j<quantity; j++) {
            //     cy.get('.btnAddToCart > .btn').should('be.visible').click();
            // }
            // cy.get('.btnAddToCart > .btn').click()
            cy.get('.menu-btn').should('be.visible').click()
            // cy.get('.menu-btn').click()
            cy.get('#cart > div > div > div:nth-child(3) > div.text-right.align-right.col.s6 > a').should('be.visible').click()
            // #cart > div > div > div:nth-child(3) > div.text-right.align-right.col.s6 > a
            // cy.get('#cart > :nth-child(1) > :nth-child(1) > :nth-child(3) > :nth-child(2) > a').click()
            cy.get('#shipEmail').type(userList[i] + '@gmail.com')
            cy.get('#shipAddr1').type(getRandomProvince())
            cy.get('#newCustomerPassword').type('12345')
            cy.get('#createCustomerAccount').click()
            cy.get('#stripeButton').should('be.visible').click()
            // cy.get('#stripeButton').click()
            // increase retry timeout?
            cy.wait(2000)
        })
    }
})
